server:
  port: 8772
  servlet:
    context-path: /${spring.application.name}
spring:
  application:
    name: bbe-customers
  jpa:
    hibernate:
      ddl-auto: create-drop
  datasource:
    url: jdbc:mysql://us-cdbr-iron-east-03.cleardb.net:3306/ad_acc9bceeaad87fd
    username: b041eb03eb7e74
    password: e07d722d
logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
